apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ogx-test-4
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: streamlit-app
          image: quay.io/rh-ee-lyoon-dh/ogx-test-4:2e1e96f95a91862dc9770505213fdae90d5151c6@sha256:800a962438d231b72130b559efd46872a194f129cf5620fbe277bf4a148242a9
