apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ogx-test-4
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: streamlit-app
          image: quay.io/rh-ee-lyoon-dh/ogx-test-4:8aba46df3a80d15e84e257fabbb5b63d9f385cfd@sha256:c2e4ba94944c9f62617669419655d2711b68720d4d0c0b9602840d5557186c7d
